// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capsule.proto

#ifndef PROTOBUF_INCLUDED_capsule_2eproto
#define PROTOBUF_INCLUDED_capsule_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_capsule_2eproto 

namespace protobuf_capsule_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_capsule_2eproto
namespace hello_world {
class CapsulePDU;
class CapsulePDUDefaultTypeInternal;
extern CapsulePDUDefaultTypeInternal _CapsulePDU_default_instance_;
}  // namespace hello_world
namespace google {
namespace protobuf {
template<> ::hello_world::CapsulePDU* Arena::CreateMaybeMessage<::hello_world::CapsulePDU>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace hello_world {

// ===================================================================

class CapsulePDU : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hello_world.CapsulePDU) */ {
 public:
  CapsulePDU();
  virtual ~CapsulePDU();

  CapsulePDU(const CapsulePDU& from);

  inline CapsulePDU& operator=(const CapsulePDU& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CapsulePDU(CapsulePDU&& from) noexcept
    : CapsulePDU() {
    *this = ::std::move(from);
  }

  inline CapsulePDU& operator=(CapsulePDU&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CapsulePDU& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CapsulePDU* internal_default_instance() {
    return reinterpret_cast<const CapsulePDU*>(
               &_CapsulePDU_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CapsulePDU* other);
  friend void swap(CapsulePDU& a, CapsulePDU& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CapsulePDU* New() const final {
    return CreateMaybeMessage<CapsulePDU>(NULL);
  }

  CapsulePDU* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CapsulePDU>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CapsulePDU& from);
  void MergeFrom(const CapsulePDU& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CapsulePDU* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string payload_in_transit = 1;
  bool has_payload_in_transit() const;
  void clear_payload_in_transit();
  static const int kPayloadInTransitFieldNumber = 1;
  const ::std::string& payload_in_transit() const;
  void set_payload_in_transit(const ::std::string& value);
  #if LANG_CXX11
  void set_payload_in_transit(::std::string&& value);
  #endif
  void set_payload_in_transit(const char* value);
  void set_payload_in_transit(const char* value, size_t size);
  ::std::string* mutable_payload_in_transit();
  ::std::string* release_payload_in_transit();
  void set_allocated_payload_in_transit(::std::string* payload_in_transit);

  // optional bytes signature = 3;
  bool has_signature() const;
  void clear_signature();
  static const int kSignatureFieldNumber = 3;
  const ::std::string& signature() const;
  void set_signature(const ::std::string& value);
  #if LANG_CXX11
  void set_signature(::std::string&& value);
  #endif
  void set_signature(const char* value);
  void set_signature(const void* value, size_t size);
  ::std::string* mutable_signature();
  ::std::string* release_signature();
  void set_allocated_signature(::std::string* signature);

  // optional bytes prevHash = 4;
  bool has_prevhash() const;
  void clear_prevhash();
  static const int kPrevHashFieldNumber = 4;
  const ::std::string& prevhash() const;
  void set_prevhash(const ::std::string& value);
  #if LANG_CXX11
  void set_prevhash(::std::string&& value);
  #endif
  void set_prevhash(const char* value);
  void set_prevhash(const void* value, size_t size);
  ::std::string* mutable_prevhash();
  ::std::string* release_prevhash();
  void set_allocated_prevhash(::std::string* prevhash);

  // optional bytes hash = 5;
  bool has_hash() const;
  void clear_hash();
  static const int kHashFieldNumber = 5;
  const ::std::string& hash() const;
  void set_hash(const ::std::string& value);
  #if LANG_CXX11
  void set_hash(::std::string&& value);
  #endif
  void set_hash(const char* value);
  void set_hash(const void* value, size_t size);
  ::std::string* mutable_hash();
  ::std::string* release_hash();
  void set_allocated_hash(::std::string* hash);

  // optional string msgType = 7;
  bool has_msgtype() const;
  void clear_msgtype();
  static const int kMsgTypeFieldNumber = 7;
  const ::std::string& msgtype() const;
  void set_msgtype(const ::std::string& value);
  #if LANG_CXX11
  void set_msgtype(::std::string&& value);
  #endif
  void set_msgtype(const char* value);
  void set_msgtype(const char* value, size_t size);
  ::std::string* mutable_msgtype();
  ::std::string* release_msgtype();
  void set_allocated_msgtype(::std::string* msgtype);

  // optional string retAddr = 8;
  bool has_retaddr() const;
  void clear_retaddr();
  static const int kRetAddrFieldNumber = 8;
  const ::std::string& retaddr() const;
  void set_retaddr(const ::std::string& value);
  #if LANG_CXX11
  void set_retaddr(::std::string&& value);
  #endif
  void set_retaddr(const char* value);
  void set_retaddr(const char* value, size_t size);
  ::std::string* mutable_retaddr();
  ::std::string* release_retaddr();
  void set_allocated_retaddr(::std::string* retaddr);

  // optional int64 sender = 2;
  bool has_sender() const;
  void clear_sender();
  static const int kSenderFieldNumber = 2;
  ::google::protobuf::int64 sender() const;
  void set_sender(::google::protobuf::int64 value);

  // optional int64 timestamp = 6;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 6;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:hello_world.CapsulePDU)
 private:
  void set_has_payload_in_transit();
  void clear_has_payload_in_transit();
  void set_has_sender();
  void clear_has_sender();
  void set_has_signature();
  void clear_has_signature();
  void set_has_prevhash();
  void clear_has_prevhash();
  void set_has_hash();
  void clear_has_hash();
  void set_has_timestamp();
  void clear_has_timestamp();
  void set_has_msgtype();
  void clear_has_msgtype();
  void set_has_retaddr();
  void clear_has_retaddr();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr payload_in_transit_;
  ::google::protobuf::internal::ArenaStringPtr signature_;
  ::google::protobuf::internal::ArenaStringPtr prevhash_;
  ::google::protobuf::internal::ArenaStringPtr hash_;
  ::google::protobuf::internal::ArenaStringPtr msgtype_;
  ::google::protobuf::internal::ArenaStringPtr retaddr_;
  ::google::protobuf::int64 sender_;
  ::google::protobuf::int64 timestamp_;
  friend struct ::protobuf_capsule_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CapsulePDU

// optional string payload_in_transit = 1;
inline bool CapsulePDU::has_payload_in_transit() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CapsulePDU::set_has_payload_in_transit() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CapsulePDU::clear_has_payload_in_transit() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CapsulePDU::clear_payload_in_transit() {
  payload_in_transit_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_payload_in_transit();
}
inline const ::std::string& CapsulePDU::payload_in_transit() const {
  // @@protoc_insertion_point(field_get:hello_world.CapsulePDU.payload_in_transit)
  return payload_in_transit_.GetNoArena();
}
inline void CapsulePDU::set_payload_in_transit(const ::std::string& value) {
  set_has_payload_in_transit();
  payload_in_transit_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hello_world.CapsulePDU.payload_in_transit)
}
#if LANG_CXX11
inline void CapsulePDU::set_payload_in_transit(::std::string&& value) {
  set_has_payload_in_transit();
  payload_in_transit_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hello_world.CapsulePDU.payload_in_transit)
}
#endif
inline void CapsulePDU::set_payload_in_transit(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_payload_in_transit();
  payload_in_transit_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hello_world.CapsulePDU.payload_in_transit)
}
inline void CapsulePDU::set_payload_in_transit(const char* value, size_t size) {
  set_has_payload_in_transit();
  payload_in_transit_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hello_world.CapsulePDU.payload_in_transit)
}
inline ::std::string* CapsulePDU::mutable_payload_in_transit() {
  set_has_payload_in_transit();
  // @@protoc_insertion_point(field_mutable:hello_world.CapsulePDU.payload_in_transit)
  return payload_in_transit_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CapsulePDU::release_payload_in_transit() {
  // @@protoc_insertion_point(field_release:hello_world.CapsulePDU.payload_in_transit)
  if (!has_payload_in_transit()) {
    return NULL;
  }
  clear_has_payload_in_transit();
  return payload_in_transit_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CapsulePDU::set_allocated_payload_in_transit(::std::string* payload_in_transit) {
  if (payload_in_transit != NULL) {
    set_has_payload_in_transit();
  } else {
    clear_has_payload_in_transit();
  }
  payload_in_transit_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), payload_in_transit);
  // @@protoc_insertion_point(field_set_allocated:hello_world.CapsulePDU.payload_in_transit)
}

// optional int64 sender = 2;
inline bool CapsulePDU::has_sender() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void CapsulePDU::set_has_sender() {
  _has_bits_[0] |= 0x00000040u;
}
inline void CapsulePDU::clear_has_sender() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void CapsulePDU::clear_sender() {
  sender_ = GOOGLE_LONGLONG(0);
  clear_has_sender();
}
inline ::google::protobuf::int64 CapsulePDU::sender() const {
  // @@protoc_insertion_point(field_get:hello_world.CapsulePDU.sender)
  return sender_;
}
inline void CapsulePDU::set_sender(::google::protobuf::int64 value) {
  set_has_sender();
  sender_ = value;
  // @@protoc_insertion_point(field_set:hello_world.CapsulePDU.sender)
}

// optional bytes signature = 3;
inline bool CapsulePDU::has_signature() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CapsulePDU::set_has_signature() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CapsulePDU::clear_has_signature() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CapsulePDU::clear_signature() {
  signature_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_signature();
}
inline const ::std::string& CapsulePDU::signature() const {
  // @@protoc_insertion_point(field_get:hello_world.CapsulePDU.signature)
  return signature_.GetNoArena();
}
inline void CapsulePDU::set_signature(const ::std::string& value) {
  set_has_signature();
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hello_world.CapsulePDU.signature)
}
#if LANG_CXX11
inline void CapsulePDU::set_signature(::std::string&& value) {
  set_has_signature();
  signature_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hello_world.CapsulePDU.signature)
}
#endif
inline void CapsulePDU::set_signature(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_signature();
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hello_world.CapsulePDU.signature)
}
inline void CapsulePDU::set_signature(const void* value, size_t size) {
  set_has_signature();
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hello_world.CapsulePDU.signature)
}
inline ::std::string* CapsulePDU::mutable_signature() {
  set_has_signature();
  // @@protoc_insertion_point(field_mutable:hello_world.CapsulePDU.signature)
  return signature_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CapsulePDU::release_signature() {
  // @@protoc_insertion_point(field_release:hello_world.CapsulePDU.signature)
  if (!has_signature()) {
    return NULL;
  }
  clear_has_signature();
  return signature_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CapsulePDU::set_allocated_signature(::std::string* signature) {
  if (signature != NULL) {
    set_has_signature();
  } else {
    clear_has_signature();
  }
  signature_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), signature);
  // @@protoc_insertion_point(field_set_allocated:hello_world.CapsulePDU.signature)
}

// optional bytes prevHash = 4;
inline bool CapsulePDU::has_prevhash() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CapsulePDU::set_has_prevhash() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CapsulePDU::clear_has_prevhash() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CapsulePDU::clear_prevhash() {
  prevhash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_prevhash();
}
inline const ::std::string& CapsulePDU::prevhash() const {
  // @@protoc_insertion_point(field_get:hello_world.CapsulePDU.prevHash)
  return prevhash_.GetNoArena();
}
inline void CapsulePDU::set_prevhash(const ::std::string& value) {
  set_has_prevhash();
  prevhash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hello_world.CapsulePDU.prevHash)
}
#if LANG_CXX11
inline void CapsulePDU::set_prevhash(::std::string&& value) {
  set_has_prevhash();
  prevhash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hello_world.CapsulePDU.prevHash)
}
#endif
inline void CapsulePDU::set_prevhash(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_prevhash();
  prevhash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hello_world.CapsulePDU.prevHash)
}
inline void CapsulePDU::set_prevhash(const void* value, size_t size) {
  set_has_prevhash();
  prevhash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hello_world.CapsulePDU.prevHash)
}
inline ::std::string* CapsulePDU::mutable_prevhash() {
  set_has_prevhash();
  // @@protoc_insertion_point(field_mutable:hello_world.CapsulePDU.prevHash)
  return prevhash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CapsulePDU::release_prevhash() {
  // @@protoc_insertion_point(field_release:hello_world.CapsulePDU.prevHash)
  if (!has_prevhash()) {
    return NULL;
  }
  clear_has_prevhash();
  return prevhash_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CapsulePDU::set_allocated_prevhash(::std::string* prevhash) {
  if (prevhash != NULL) {
    set_has_prevhash();
  } else {
    clear_has_prevhash();
  }
  prevhash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), prevhash);
  // @@protoc_insertion_point(field_set_allocated:hello_world.CapsulePDU.prevHash)
}

// optional bytes hash = 5;
inline bool CapsulePDU::has_hash() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CapsulePDU::set_has_hash() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CapsulePDU::clear_has_hash() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CapsulePDU::clear_hash() {
  hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_hash();
}
inline const ::std::string& CapsulePDU::hash() const {
  // @@protoc_insertion_point(field_get:hello_world.CapsulePDU.hash)
  return hash_.GetNoArena();
}
inline void CapsulePDU::set_hash(const ::std::string& value) {
  set_has_hash();
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hello_world.CapsulePDU.hash)
}
#if LANG_CXX11
inline void CapsulePDU::set_hash(::std::string&& value) {
  set_has_hash();
  hash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hello_world.CapsulePDU.hash)
}
#endif
inline void CapsulePDU::set_hash(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_hash();
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hello_world.CapsulePDU.hash)
}
inline void CapsulePDU::set_hash(const void* value, size_t size) {
  set_has_hash();
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hello_world.CapsulePDU.hash)
}
inline ::std::string* CapsulePDU::mutable_hash() {
  set_has_hash();
  // @@protoc_insertion_point(field_mutable:hello_world.CapsulePDU.hash)
  return hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CapsulePDU::release_hash() {
  // @@protoc_insertion_point(field_release:hello_world.CapsulePDU.hash)
  if (!has_hash()) {
    return NULL;
  }
  clear_has_hash();
  return hash_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CapsulePDU::set_allocated_hash(::std::string* hash) {
  if (hash != NULL) {
    set_has_hash();
  } else {
    clear_has_hash();
  }
  hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hash);
  // @@protoc_insertion_point(field_set_allocated:hello_world.CapsulePDU.hash)
}

// optional int64 timestamp = 6;
inline bool CapsulePDU::has_timestamp() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void CapsulePDU::set_has_timestamp() {
  _has_bits_[0] |= 0x00000080u;
}
inline void CapsulePDU::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void CapsulePDU::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::int64 CapsulePDU::timestamp() const {
  // @@protoc_insertion_point(field_get:hello_world.CapsulePDU.timestamp)
  return timestamp_;
}
inline void CapsulePDU::set_timestamp(::google::protobuf::int64 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:hello_world.CapsulePDU.timestamp)
}

// optional string msgType = 7;
inline bool CapsulePDU::has_msgtype() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CapsulePDU::set_has_msgtype() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CapsulePDU::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CapsulePDU::clear_msgtype() {
  msgtype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_msgtype();
}
inline const ::std::string& CapsulePDU::msgtype() const {
  // @@protoc_insertion_point(field_get:hello_world.CapsulePDU.msgType)
  return msgtype_.GetNoArena();
}
inline void CapsulePDU::set_msgtype(const ::std::string& value) {
  set_has_msgtype();
  msgtype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hello_world.CapsulePDU.msgType)
}
#if LANG_CXX11
inline void CapsulePDU::set_msgtype(::std::string&& value) {
  set_has_msgtype();
  msgtype_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hello_world.CapsulePDU.msgType)
}
#endif
inline void CapsulePDU::set_msgtype(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_msgtype();
  msgtype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hello_world.CapsulePDU.msgType)
}
inline void CapsulePDU::set_msgtype(const char* value, size_t size) {
  set_has_msgtype();
  msgtype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hello_world.CapsulePDU.msgType)
}
inline ::std::string* CapsulePDU::mutable_msgtype() {
  set_has_msgtype();
  // @@protoc_insertion_point(field_mutable:hello_world.CapsulePDU.msgType)
  return msgtype_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CapsulePDU::release_msgtype() {
  // @@protoc_insertion_point(field_release:hello_world.CapsulePDU.msgType)
  if (!has_msgtype()) {
    return NULL;
  }
  clear_has_msgtype();
  return msgtype_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CapsulePDU::set_allocated_msgtype(::std::string* msgtype) {
  if (msgtype != NULL) {
    set_has_msgtype();
  } else {
    clear_has_msgtype();
  }
  msgtype_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msgtype);
  // @@protoc_insertion_point(field_set_allocated:hello_world.CapsulePDU.msgType)
}

// optional string retAddr = 8;
inline bool CapsulePDU::has_retaddr() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CapsulePDU::set_has_retaddr() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CapsulePDU::clear_has_retaddr() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CapsulePDU::clear_retaddr() {
  retaddr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_retaddr();
}
inline const ::std::string& CapsulePDU::retaddr() const {
  // @@protoc_insertion_point(field_get:hello_world.CapsulePDU.retAddr)
  return retaddr_.GetNoArena();
}
inline void CapsulePDU::set_retaddr(const ::std::string& value) {
  set_has_retaddr();
  retaddr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hello_world.CapsulePDU.retAddr)
}
#if LANG_CXX11
inline void CapsulePDU::set_retaddr(::std::string&& value) {
  set_has_retaddr();
  retaddr_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hello_world.CapsulePDU.retAddr)
}
#endif
inline void CapsulePDU::set_retaddr(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_retaddr();
  retaddr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hello_world.CapsulePDU.retAddr)
}
inline void CapsulePDU::set_retaddr(const char* value, size_t size) {
  set_has_retaddr();
  retaddr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hello_world.CapsulePDU.retAddr)
}
inline ::std::string* CapsulePDU::mutable_retaddr() {
  set_has_retaddr();
  // @@protoc_insertion_point(field_mutable:hello_world.CapsulePDU.retAddr)
  return retaddr_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CapsulePDU::release_retaddr() {
  // @@protoc_insertion_point(field_release:hello_world.CapsulePDU.retAddr)
  if (!has_retaddr()) {
    return NULL;
  }
  clear_has_retaddr();
  return retaddr_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CapsulePDU::set_allocated_retaddr(::std::string* retaddr) {
  if (retaddr != NULL) {
    set_has_retaddr();
  } else {
    clear_has_retaddr();
  }
  retaddr_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), retaddr);
  // @@protoc_insertion_point(field_set_allocated:hello_world.CapsulePDU.retAddr)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace hello_world

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_capsule_2eproto
