// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capsule.proto

#include "capsule.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace hello_world {
class CapsulePDUDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CapsulePDU>
      _instance;
} _CapsulePDU_default_instance_;
}  // namespace hello_world
namespace protobuf_capsule_2eproto {
static void InitDefaultsCapsulePDU() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::hello_world::_CapsulePDU_default_instance_;
    new (ptr) ::hello_world::CapsulePDU();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::hello_world::CapsulePDU::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CapsulePDU =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCapsulePDU}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_CapsulePDU.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::hello_world::CapsulePDU, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::hello_world::CapsulePDU, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::hello_world::CapsulePDU, payload_in_transit_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::hello_world::CapsulePDU, sender_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::hello_world::CapsulePDU, signature_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::hello_world::CapsulePDU, prevhash_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::hello_world::CapsulePDU, hash_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::hello_world::CapsulePDU, timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::hello_world::CapsulePDU, msgtype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::hello_world::CapsulePDU, retaddr_),
  0,
  6,
  1,
  2,
  3,
  7,
  4,
  5,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 13, sizeof(::hello_world::CapsulePDU)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::hello_world::_CapsulePDU_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "capsule.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\rcapsule.proto\022\013hello_world\"\240\001\n\nCapsule"
      "PDU\022\032\n\022payload_in_transit\030\001 \001(\t\022\016\n\006sende"
      "r\030\002 \001(\003\022\021\n\tsignature\030\003 \001(\014\022\020\n\010prevHash\030\004"
      " \001(\014\022\014\n\004hash\030\005 \001(\014\022\021\n\ttimestamp\030\006 \001(\003\022\017\n"
      "\007msgType\030\007 \001(\t\022\017\n\007retAddr\030\010 \001(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 191);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "capsule.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_capsule_2eproto
namespace hello_world {

// ===================================================================

void CapsulePDU::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CapsulePDU::kPayloadInTransitFieldNumber;
const int CapsulePDU::kSenderFieldNumber;
const int CapsulePDU::kSignatureFieldNumber;
const int CapsulePDU::kPrevHashFieldNumber;
const int CapsulePDU::kHashFieldNumber;
const int CapsulePDU::kTimestampFieldNumber;
const int CapsulePDU::kMsgTypeFieldNumber;
const int CapsulePDU::kRetAddrFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CapsulePDU::CapsulePDU()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_capsule_2eproto::scc_info_CapsulePDU.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:hello_world.CapsulePDU)
}
CapsulePDU::CapsulePDU(const CapsulePDU& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  payload_in_transit_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_payload_in_transit()) {
    payload_in_transit_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.payload_in_transit_);
  }
  signature_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_signature()) {
    signature_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.signature_);
  }
  prevhash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_prevhash()) {
    prevhash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.prevhash_);
  }
  hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_hash()) {
    hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hash_);
  }
  msgtype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_msgtype()) {
    msgtype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msgtype_);
  }
  retaddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_retaddr()) {
    retaddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.retaddr_);
  }
  ::memcpy(&sender_, &from.sender_,
    static_cast<size_t>(reinterpret_cast<char*>(&timestamp_) -
    reinterpret_cast<char*>(&sender_)) + sizeof(timestamp_));
  // @@protoc_insertion_point(copy_constructor:hello_world.CapsulePDU)
}

void CapsulePDU::SharedCtor() {
  payload_in_transit_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  signature_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  prevhash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msgtype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  retaddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&sender_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&timestamp_) -
      reinterpret_cast<char*>(&sender_)) + sizeof(timestamp_));
}

CapsulePDU::~CapsulePDU() {
  // @@protoc_insertion_point(destructor:hello_world.CapsulePDU)
  SharedDtor();
}

void CapsulePDU::SharedDtor() {
  payload_in_transit_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  signature_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  prevhash_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hash_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msgtype_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  retaddr_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CapsulePDU::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CapsulePDU::descriptor() {
  ::protobuf_capsule_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_capsule_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CapsulePDU& CapsulePDU::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_capsule_2eproto::scc_info_CapsulePDU.base);
  return *internal_default_instance();
}


void CapsulePDU::Clear() {
// @@protoc_insertion_point(message_clear_start:hello_world.CapsulePDU)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 63u) {
    if (cached_has_bits & 0x00000001u) {
      payload_in_transit_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      signature_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000004u) {
      prevhash_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000008u) {
      hash_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000010u) {
      msgtype_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000020u) {
      retaddr_.ClearNonDefaultToEmptyNoArena();
    }
  }
  if (cached_has_bits & 192u) {
    ::memset(&sender_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&timestamp_) -
        reinterpret_cast<char*>(&sender_)) + sizeof(timestamp_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool CapsulePDU::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hello_world.CapsulePDU)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string payload_in_transit = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_payload_in_transit()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->payload_in_transit().data(), static_cast<int>(this->payload_in_transit().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "hello_world.CapsulePDU.payload_in_transit");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int64 sender = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_sender();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &sender_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bytes signature = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_signature()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bytes prevHash = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_prevhash()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bytes hash = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_hash()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int64 timestamp = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {
          set_has_timestamp();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string msgType = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msgtype()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->msgtype().data(), static_cast<int>(this->msgtype().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "hello_world.CapsulePDU.msgType");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string retAddr = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_retaddr()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->retaddr().data(), static_cast<int>(this->retaddr().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "hello_world.CapsulePDU.retAddr");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hello_world.CapsulePDU)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hello_world.CapsulePDU)
  return false;
#undef DO_
}

void CapsulePDU::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hello_world.CapsulePDU)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string payload_in_transit = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->payload_in_transit().data(), static_cast<int>(this->payload_in_transit().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hello_world.CapsulePDU.payload_in_transit");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->payload_in_transit(), output);
  }

  // optional int64 sender = 2;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->sender(), output);
  }

  // optional bytes signature = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->signature(), output);
  }

  // optional bytes prevHash = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->prevhash(), output);
  }

  // optional bytes hash = 5;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      5, this->hash(), output);
  }

  // optional int64 timestamp = 6;
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(6, this->timestamp(), output);
  }

  // optional string msgType = 7;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->msgtype().data(), static_cast<int>(this->msgtype().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hello_world.CapsulePDU.msgType");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->msgtype(), output);
  }

  // optional string retAddr = 8;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->retaddr().data(), static_cast<int>(this->retaddr().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hello_world.CapsulePDU.retAddr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->retaddr(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:hello_world.CapsulePDU)
}

::google::protobuf::uint8* CapsulePDU::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:hello_world.CapsulePDU)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string payload_in_transit = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->payload_in_transit().data(), static_cast<int>(this->payload_in_transit().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hello_world.CapsulePDU.payload_in_transit");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->payload_in_transit(), target);
  }

  // optional int64 sender = 2;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->sender(), target);
  }

  // optional bytes signature = 3;
  if (cached_has_bits & 0x00000002u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->signature(), target);
  }

  // optional bytes prevHash = 4;
  if (cached_has_bits & 0x00000004u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->prevhash(), target);
  }

  // optional bytes hash = 5;
  if (cached_has_bits & 0x00000008u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        5, this->hash(), target);
  }

  // optional int64 timestamp = 6;
  if (cached_has_bits & 0x00000080u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(6, this->timestamp(), target);
  }

  // optional string msgType = 7;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->msgtype().data(), static_cast<int>(this->msgtype().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hello_world.CapsulePDU.msgType");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->msgtype(), target);
  }

  // optional string retAddr = 8;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->retaddr().data(), static_cast<int>(this->retaddr().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hello_world.CapsulePDU.retAddr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->retaddr(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hello_world.CapsulePDU)
  return target;
}

size_t CapsulePDU::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hello_world.CapsulePDU)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 255u) {
    // optional string payload_in_transit = 1;
    if (has_payload_in_transit()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->payload_in_transit());
    }

    // optional bytes signature = 3;
    if (has_signature()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->signature());
    }

    // optional bytes prevHash = 4;
    if (has_prevhash()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->prevhash());
    }

    // optional bytes hash = 5;
    if (has_hash()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->hash());
    }

    // optional string msgType = 7;
    if (has_msgtype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->msgtype());
    }

    // optional string retAddr = 8;
    if (has_retaddr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->retaddr());
    }

    // optional int64 sender = 2;
    if (has_sender()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->sender());
    }

    // optional int64 timestamp = 6;
    if (has_timestamp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->timestamp());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CapsulePDU::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hello_world.CapsulePDU)
  GOOGLE_DCHECK_NE(&from, this);
  const CapsulePDU* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CapsulePDU>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hello_world.CapsulePDU)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hello_world.CapsulePDU)
    MergeFrom(*source);
  }
}

void CapsulePDU::MergeFrom(const CapsulePDU& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hello_world.CapsulePDU)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_payload_in_transit();
      payload_in_transit_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.payload_in_transit_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_signature();
      signature_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.signature_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_prevhash();
      prevhash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.prevhash_);
    }
    if (cached_has_bits & 0x00000008u) {
      set_has_hash();
      hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hash_);
    }
    if (cached_has_bits & 0x00000010u) {
      set_has_msgtype();
      msgtype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msgtype_);
    }
    if (cached_has_bits & 0x00000020u) {
      set_has_retaddr();
      retaddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.retaddr_);
    }
    if (cached_has_bits & 0x00000040u) {
      sender_ = from.sender_;
    }
    if (cached_has_bits & 0x00000080u) {
      timestamp_ = from.timestamp_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void CapsulePDU::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hello_world.CapsulePDU)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CapsulePDU::CopyFrom(const CapsulePDU& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hello_world.CapsulePDU)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CapsulePDU::IsInitialized() const {
  return true;
}

void CapsulePDU::Swap(CapsulePDU* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CapsulePDU::InternalSwap(CapsulePDU* other) {
  using std::swap;
  payload_in_transit_.Swap(&other->payload_in_transit_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  signature_.Swap(&other->signature_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  prevhash_.Swap(&other->prevhash_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  hash_.Swap(&other->hash_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  msgtype_.Swap(&other->msgtype_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  retaddr_.Swap(&other->retaddr_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(sender_, other->sender_);
  swap(timestamp_, other->timestamp_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CapsulePDU::GetMetadata() const {
  protobuf_capsule_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_capsule_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace hello_world
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::hello_world::CapsulePDU* Arena::CreateMaybeMessage< ::hello_world::CapsulePDU >(Arena* arena) {
  return Arena::CreateInternal< ::hello_world::CapsulePDU >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
